# This creates a VPC with two subnets, one public and one private, each with associated route tables.
# The public subnet has an Internet Gateway attached.

# Each subnet has a rule attached, additional rules should be added for use in production. Recommended rules for different scenarios:
# http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_NACLs.html

---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample CloudFormation template'

Resources:
  # VPC everything will go into, or get attached to.
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId

  # A private subnet isn't exposed to the Internet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      Tags:
      - Key: Type
        Value: 'private'
      - Key: Application
        Value:
          Ref: AWS::StackId
          
  # Add a route table for the public subnet. We'll add routes to it below.
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId
          
  # The foot bone is connected to the heel bone... attach the route table to the subnet
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateRouteTable
        
  # Add a NAT gateway to the private subnet if you want to allow communication out, like to APIs

  # A public subnet is just a subnet with an Internet Gateway attached, which we'll do below
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.90/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Type
        Value: 'public'
      - Key: Application
        Value:
          Ref: AWS::StackId
          
  # A route table is a set of rules (aka routes) to direct network traffic. Every subnet needs to be connected to a route table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId
          
  # The foot bone is connected to the heel bone... attach the route table to the subnet
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicRouteTable

  # Add the Internet Gateway to make the public subnet Internet accessible
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId

  # The toe bone is connected to the foot bone... attach the Internet Gateway to the VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  # Cidr block 0.0.0.0/0 is the whole Internet. This route opens the Internet Gateway to the all Internet traffic
  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

Outputs:
  VPCId:
    Value: !Ref VPC

  PublicSubnetId:
    Value: !Ref PublicSubnet
